version: "3.5"

services:
  hugo:
      image: klakegg/hugo:0.107.0-ext-ubuntu
      command: server -D -F -E --poll 700ms --disableFastRender
      container_name: hugo
      volumes:
        - ".:/src"
      ports:
        - "1313:1313"
      networks:
        - hugonet
networks:
  hugonet:
    name: hugo-network